target 'MMSCameraViewController_Example' do
platform :ios, '9.0'
use_frameworks!
pod 'SwiftLint'

  pod 'MMSCameraViewController', :path => '../'

  target 'MMSCameraViewController_Tests' do
    inherit! :search_paths
  end
end
