target 'MMSCameraViewController_Example' do
use_frameworks!
pod 'SwiftLint'

  pod 'MMSCameraViewController', :path => '../'

  target 'MMSCameraViewController_Tests' do
    inherit! :search_paths
  end
end
